// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1Z34gIp8xK4Expf2OUrqfMe9jeZqC14',
    appId: '1:371815697931:web:f33f3fb2ac0efc9473c10e',
    messagingSenderId: '371815697931',
    projectId: 'keuangan-e5487',
    authDomain: 'keuangan-e5487.firebaseapp.com',
    storageBucket: 'keuangan-e5487.appspot.com',
    measurementId: 'G-935V70PS63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5p40RVndXMDBDosrgjffA8VXeAcpJVrQ',
    appId: '1:371815697931:android:640afa98fe2e44de73c10e',
    messagingSenderId: '371815697931',
    projectId: 'keuangan-e5487',
    storageBucket: 'keuangan-e5487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEK47rkmGnHIpKmRNezxGPHR4iDk9JQ9g',
    appId: '1:371815697931:ios:b7c56b4005ffadc473c10e',
    messagingSenderId: '371815697931',
    projectId: 'keuangan-e5487',
    storageBucket: 'keuangan-e5487.appspot.com',
    iosBundleId: 'com.example.testingBolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEK47rkmGnHIpKmRNezxGPHR4iDk9JQ9g',
    appId: '1:371815697931:ios:56bc65f0c5fe906f73c10e',
    messagingSenderId: '371815697931',
    projectId: 'keuangan-e5487',
    storageBucket: 'keuangan-e5487.appspot.com',
    iosBundleId: 'com.example.testingBolo.RunnerTests',
  );
}
